trainer:
  max_epochs: 6
  log_every_n_steps: 1
  check_val_every_n_epoch: 3
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: ./logs
      name: examples
      log_graph: true
model:
  class_path: fmp.models.ResNet18Classifier
  init_args:
    num_classes: 24
data:
  class_path: fmp.datasets.fingerspelling5.Fingerspelling5ImageDataModule
  init_args:
    datasplit_file: ./data/fingerspelling5/fingerspelling5_dummy/split_00_fingerspelling5_dummy.csv
    images_data_dir: ../../data/
    dataquality_file: ./data/fingerspelling5/fingerspelling5_dummy/fingerspelling5_dummy__data_quality.csv
    batch_size: 64
    num_dataloader_workers: 23
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.001
lr_scheduler:
  class_path: torch.optim.lr_scheduler.CosineAnnealingLR
  init_args:
    T_max: 20
