# lightning.pytorch==2.2.1
trainer:
  callbacks:
    - class_path: fmp.lit_tools.callbacks.Fingerspelling5PredictionWriter
      init_args:
        write_interval: epoch
        output_dir: ./predictions/example/vision_dummy
  logger: null
data:
  class_path: fmp.datasets.fingerspelling5.Fingerspelling5ImageDataModule
  init_args:
    dataset_dir: ./data/fingerspelling5/fingerspelling5_dummy
    images_data_dir: ../../data/
    datasplit_file: null
    dataquality_file: null
    batch_size: 64
    predict_transforms: null
return_predictions: False
