# lightning.pytorch==2.2.1
trainer:
  max_epochs: 20
  log_every_n_steps: 1
  check_val_every_n_epoch: 3
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: /home/micha/projects/messy-stuff/
model:
  input_dim: 63
  hidden_dim: 10
  output_dim: 24
data:
  fingerspelling5_csv: /home/micha/projects/messy-stuff/data/fingerspelling5_dummy_data.csv
  batch_size: 128
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.001
lr_scheduler:
  class_path: torch.optim.lr_scheduler.CosineAnnealingLR
  init_args:
    T_max: 20
